<!DOCTYPE html>
<html lang="en">
	
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ReconDash - Tool configuration settings</title>
    <link rel="stylesheet" href="/css/main.css">
</head>
	
<body>
<div class="container">
<center>
<hr>
  <header>
    <h1>ReconDash</h1>
    <p class="subtitle"><b>ReconDash</b> - <i>Tool configuration settings</i></p>
  </header>
 <hr>      
 <br />
   <form action="/exec_all.php">
    <input type="checkbox" id="tool1" name="tool1" value="tool1">
    <label for="tool1"> ENABLE TOOL #1 </label><br>
    <input type="checkbox" id="tool2" name="tool2" value="too11">
    <label for="tool2"> ENABLE TOOL #2 </label><br>
      <!-- ... AND SO ON -->    
    <input type="submit" value="Submit">
   </form>
</center>
</div>
</body>
</html>
